// == info.js v1.0.7 ==
(function(){
  const Info = {
    extra:null, go:null, mode:null,
    typeState:{attack:'fire', def1:'grass', def2:''},
    pokedexQuery:'', pokedexGen:'all', pokedexCategory:'all', pageSize:'100', selectedPokemon:null,
    iv:{attack:15, defense:15, stamina:15}, level:50, composing:false
  };
  const typeColors={normal:'#A8A77A',fire:'#EE8130',water:'#6390F0',electric:'#F7D02C',grass:'#7AC74C',ice:'#96D9D6',fighting:'#C22E28',poison:'#A33EA1',ground:'#E2BF65',flying:'#A98FF3',psychic:'#F95587',bug:'#A6B91A',rock:'#B6A136',ghost:'#735797',dragon:'#6F35FC',dark:'#705746',steel:'#B7B7CE',fairy:'#D685AD'};
  const labels={
    'zh-CN':{types:'属性克制',pokedex:'宝可梦图鉴',attackView:'攻击视角',defenseView:'防御视角',attackType:'攻击属性',defender:'防御属性',none:'无',multiplier:'伤害倍率',search:'搜索名称 / 编号 / 属性',showing:'显示',rows:'行',generation:'世代',category:'特殊类别',all:'全部',pageSize:'显示',super2:'超级有效',super1:'有效',normal:'一般',resist1:'抗性',resist2:'超级抗性',selectedDefense:'当前防御组合',cpCalc:'CP 计算器',level:'等级',source:'CP = floor((攻击+IV) × √(防御+IV) × √(生命+IV) × CPM² / 10)',stars:'评价',goStats:'GO 种族值'},
    'zh-TW':{types:'屬性克制',pokedex:'寶可夢圖鑑',attackView:'攻擊視角',defenseView:'防禦視角',attackType:'攻擊屬性',defender:'防禦屬性',none:'無',multiplier:'傷害倍率',search:'搜尋名稱 / 編號 / 屬性',showing:'顯示',rows:'列',generation:'世代',category:'特殊類別',all:'全部',pageSize:'顯示',super2:'超級有效',super1:'有效',normal:'一般',resist1:'抗性',resist2:'超級抗性',selectedDefense:'目前防禦組合',cpCalc:'CP 計算器',level:'等級',source:'CP = floor((攻擊+IV) × √(防禦+IV) × √(生命+IV) × CPM² / 10)',stars:'評價',goStats:'GO 種族值'},
    en:{types:'Type Chart',pokedex:'Pokédex',attackView:'Attack view',defenseView:'Defense view',attackType:'Attack type',defender:'Defense type',none:'None',multiplier:'Damage multiplier',search:'Search name / number / type',showing:'Showing',rows:'rows',generation:'Generation',category:'Special category',all:'All',pageSize:'Show',super2:'Double super effective',super1:'Super effective',normal:'Neutral',resist1:'Resisted',resist2:'Double resisted',selectedDefense:'Current defense',cpCalc:'CP Calculator',level:'Level',source:'CP = floor((Attack+IV) × √(Defense+IV) × √(Stamina+IV) × CPM² / 10)',stars:'Rating',goStats:'GO base stats'}
  };
  function lang(){ return (Info.opts && Info.opts.getLang && Info.opts.getLang()) || (window.LDT_Core && LDT_Core.DEFAULT_LANG) || 'zh-CN'; }
  function t(k){ const l=lang(); return (labels[l]||labels.en)[k] || labels.en[k] || k; }
  function esc(v){ return String(v==null?'':v).replace(/[&<>"']/g, ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch])); }
  function typeLabel(type){ const l=lang(); return type && (type[l] || type['zh-CN'] || type.en || type.key) || ''; }
  function typeByKey(k){ return (Info.extra && Info.extra.types || []).find(x=>x.key===k); }
  function badge(k){ const ty=typeByKey(k); if(!ty) return ''; return `<span class="nd-type-badge" style="--nd-type-color:${typeColors[k]||'#889'}">${esc(typeLabel(ty))}</span>`; }
  function fmtMul(v){ if(!isFinite(v)) return ''; return (Math.round(v*100)/100).toString().replace(/\.00$/,'').replace(/(\.\d)0$/,'$1'); }
  function effClass(v){ if(v>1.01) return 'nd-eff-high'; if(v<0.625) return 'nd-eff-immune'; if(v<0.99) return 'nd-eff-low'; return 'nd-eff-one'; }
  async function fetchJson(path){ let url=path; try{ if(typeof chrome!=='undefined' && chrome.runtime && chrome.runtime.getURL) url=chrome.runtime.getURL(path); }catch(_){ } const res=await fetch(url); const txt=await res.text(); return txt.trim()?JSON.parse(txt):{}; }
  async function loadData(){ if(!Info.extra) Info.extra=await fetchJson('assets/pokemon_extra.json'); if(!Info.go) Info.go=await fetchJson('assets/pokemon_go.json'); return Info; }
  function ensureUI(){ const right=document.getElementById('ld-right'); if(!right) return false; if(!document.getElementById('ld-info-panel')){ const panel=document.createElement('div'); panel.id='ld-info-panel'; panel.style.display='none'; right.appendChild(panel); } return true; }
  function hide(){ const p=document.getElementById('ld-info-panel'); if(p) p.style.display='none'; Info.mode=null; }
  function showOnlyPanel(){ const svg=document.getElementById('ld-timeline-svg'), mg=document.getElementById('ld-monthgrid'), ext=document.getElementById('ld-extenders'), p=document.getElementById('ld-info-panel'), left=document.getElementById('ld-left'), right=document.getElementById('ld-right'); if(svg) svg.style.display='none'; if(mg) mg.style.display='none'; if(ext) ext.style.display='none'; if(left) left.style.display='none'; if(right) right.style.gridColumn='1 / span 2'; if(p) p.style.display='block'; }
  Info.show = async function(mode){ if(!ensureUI()) return; Info.mode=mode==='pokedex'?'pokedex':'types'; showOnlyPanel(); await loadData(); const p=document.getElementById('ld-info-panel'); if(Info.mode==='pokedex') renderPokedex(p); else renderTypes(p); };
  Info.hide = function(){ const ext=document.getElementById('ld-extenders'), left=document.getElementById('ld-left'), right=document.getElementById('ld-right'); if(ext) ext.style.display='block'; if(left) left.style.display='block'; if(right) right.style.gridColumn='2'; hide(); };
  Info.refreshLabels=function(){ if(Info.mode){ const p=document.getElementById('ld-info-panel'); if(p) (Info.mode==='pokedex'?renderPokedex:renderTypes)(p); } };
  function mult(atk, d1, d2){ const m=Info.extra.typeChart; if(!atk||!d1) return null; return (m[atk]?.[d1]??1) * (d2 ? (m[atk]?.[d2]??1) : 1); }
  function pickDefense(k){ const st=Info.typeState; if(k===st.def1){ if(st.def2){ st.def1=st.def2; st.def2=''; } return; } if(k===st.def2){ st.def2=''; return; } if(!st.def1){ st.def1=k; return; } if(!st.def2){ st.def2=k; return; } st.def1=k; st.def2=''; }
  function renderTypes(panel){
    const st=Info.typeState, types=Info.extra.types, chart=Info.extra.typeChart;
    const selectedMult=mult(st.attack, st.def1, st.def2) || 1;
    const header=types.map(ty=>`<th class="${st.def1===ty.key||st.def2===ty.key?'nd-selected-col':''}" data-def="${esc(ty.key)}">${badge(ty.key)}</th>`).join('');
    const rows=types.map(at=>{ const cells=types.map(df=>{ const v=chart[at.key]?.[df.key]??1; const sel=(st.attack===at.key && (st.def1===df.key||st.def2===df.key)); return `<td class="${effClass(v)} ${sel?'nd-selected-cell':''} ${st.def1===df.key||st.def2===df.key?'nd-selected-col':''}" data-atk="${esc(at.key)}" data-def="${esc(df.key)}">${fmtMul(v)}</td>`; }).join(''); return `<tr><th class="${st.attack===at.key?'nd-selected-row':''}" data-atk="${esc(at.key)}">${badge(at.key)}</th>${cells}</tr>`; }).join('');
    const groups={super2:[],super1:[],normal:[],resist1:[],resist2:[]};
    for(const atk of types){ const v=mult(atk.key, st.def1, st.def2)||1; if(v>=2.55) groups.super2.push(atk.key); else if(v>1.01) groups.super1.push(atk.key); else if(Math.abs(v-1)<0.01) groups.normal.push(atk.key); else if(v<=0.40) groups.resist2.push(atk.key); else groups.resist1.push(atk.key); }
    const groupHtml=Object.keys(groups).map(k=>`<div class="nd-defense-group"><b>${esc(t(k))}</b><div>${groups[k].length?groups[k].map(badge).join(''):'-'}</div></div>`).join('');
    panel.innerHTML=`<div class="nd-info-layout nd-types-layout"><div class="nd-info-main"><h2>${esc(t('types'))}</h2><div class="nd-table-scroll nd-type-scroll"><table class="nd-type-chart"><thead><tr><th>ATK \\ DEF</th>${header}</tr></thead><tbody>${rows}</tbody></table></div></div><aside class="nd-info-side nd-type-side"><section class="nd-card nd-attack-card"><h3>${esc(t('attackView'))}</h3><div class="nd-selected-line"><b>${esc(t('attackType'))}</b>${badge(st.attack)}</div><div class="nd-selected-line"><b>${esc(t('defender'))}</b>${badge(st.def1)}${st.def2?badge(st.def2):''}</div><div class="nd-big-mult ${effClass(selectedMult)}">${fmtMul(selectedMult)}×</div></section><section class="nd-card nd-defense-card"><h3>${esc(t('defenseView'))}</h3><div class="nd-selected-line"><b>${esc(t('selectedDefense'))}</b>${badge(st.def1)}${st.def2?badge(st.def2):''}</div><div class="nd-defense-list">${groupHtml}</div></section></aside></div>`;
    panel.querySelectorAll('[data-atk]').forEach(el=>el.addEventListener('click',()=>{ Info.typeState.attack=el.getAttribute('data-atk'); renderTypes(panel); }));
    panel.querySelectorAll('[data-def]').forEach(el=>el.addEventListener('click',(ev)=>{ ev.stopPropagation(); pickDefense(el.getAttribute('data-def')); renderTypes(panel); }));
  }
  function categoryMatch(row){ const c=Info.pokedexCategory; if(c==='all') return true; if(c==='legendary_mythical') return (row.categories||[]).includes('legendary') || (row.categories||[]).includes('mythical'); return (row.categories||[]).includes(c); }
  function filteredRows(){ const q=Info.pokedexQuery.trim().toLowerCase(); return (Info.go.rows||[]).filter(r=>(Info.pokedexGen==='all'||String(r.generation)===String(Info.pokedexGen)) && categoryMatch(r) && (!q || String(r.search||'').includes(q))); }
  function cpm(level){ const key=String(Number(level)); return Number((Info.go.cpm||{})[key] || (Info.go.cpm||{})[String(Math.round(Number(level)*2)/2)] || (Info.go.cpm||{})['50'] || 0.84029999); }
  function calcCP(row){ const m=cpm(Info.level); const a=Number(row.goAttack)+Number(Info.iv.attack), d=Number(row.goDefense)+Number(Info.iv.defense), s=Number(row.goStamina)+Number(Info.iv.stamina); return Math.max(10, Math.floor(a*Math.sqrt(d)*Math.sqrt(s)*m*m/10)); }
  function starRating(){ const sum=Number(Info.iv.attack)+Number(Info.iv.defense)+Number(Info.iv.stamina); if(sum===45) return {n:4, cls:'four'}; if(sum>=37) return {n:3, cls:'three'}; if(sum>=30) return {n:2, cls:'two'}; if(sum>=23) return {n:1, cls:'one'}; return {n:0, cls:'zero'}; }
  function radar(row){ const vals=[Number(row.goAttack),Number(row.goDefense),Number(row.goStamina)], max=Math.max(320,...vals); const cx=92, cy=82, r=62; const pts=vals.map((v,i)=>{ const a=-Math.PI/2+i*2*Math.PI/3; const rr=r*v/max; return [cx+Math.cos(a)*rr, cy+Math.sin(a)*rr]; }); const frame=[0,1,2].map(i=>{const a=-Math.PI/2+i*2*Math.PI/3; return [cx+Math.cos(a)*r, cy+Math.sin(a)*r];}); return `<svg class="nd-radar" viewBox="0 0 184 160"><polygon points="${frame.map(p=>p.join(',')).join(' ')}" class="nd-radar-frame"/><polygon points="${pts.map(p=>p.join(',')).join(' ')}" class="nd-radar-poly"/><text x="92" y="13" text-anchor="middle">ATK ${row.goAttack}</text><text x="30" y="145" text-anchor="middle">DEF ${row.goDefense}</text><text x="154" y="145" text-anchor="middle">HP ${row.goStamina}</text></svg>`; }
  function ivSlider(key,label){ const v=Info.iv[key]; const filled=Math.max(0,Math.min(15,Number(v))); const segs=Array.from({length:15},(_,i)=>`<span class="${i<filled?'on':''}"></span>`).join(''); return `<label class="nd-iv-row"><span>${esc(label)} IV <b>${v}</b></span><input type="range" min="0" max="15" step="1" value="${v}" data-iv="${key}"><div class="nd-iv-segments">${segs}</div></label>`; }
  function renderCalculator(row){ if(!row) return ''; const cp=calcCP(row), rating=starRating(); return `<section class="nd-card nd-cp-card"><h3>${esc(t('cpCalc'))}</h3><div class="nd-poke-title"><b>${esc(row.displayName)}</b><span>#${esc(row.dex)}</span></div>${radar(row)}<div class="nd-go-stats">${esc(t('goStats'))}: ${row.goAttack} / ${row.goDefense} / ${row.goStamina}</div>${ivSlider('attack','Attack')}${ivSlider('defense','Defense')}${ivSlider('stamina','HP')}<label class="nd-level-row"><span>${esc(t('level'))}</span><input data-level type="number" min="1" max="51" step="0.5" value="${esc(Info.level)}"></label><div class="nd-cp-result">CP <b>${cp}</b></div><div class="nd-stars ${rating.cls}">${'★'.repeat(rating.n)}${'☆'.repeat(4-rating.n)} <span>${esc(t('stars'))}</span></div><p class="nd-formula">${esc(t('source'))}<br><a href="https://www.dittobase.com/pokemon-go/cp-calculator" target="_blank" rel="noopener">Dittobase CP Calculator</a> · <a href="https://pokemongohub.net/post/wiki/pokemon-go-calculates-stats-max-cp/" target="_blank" rel="noopener">Pokémon GO Hub formula</a></p></section>`; }
  function renderPokedex(panel){
    if(!Info.selectedPokemon) Info.selectedPokemon=(Info.go.rows||[]).find(r=>String(r.name).toLowerCase()==='pikachu' && !r.form) || (Info.go.rows||[])[0];
    const all=filteredRows(); const limit=Info.pageSize==='all'?all.length:Number(Info.pageSize||100); const rows=all.slice(0, limit);
    const genOpts=[`<option value="all">${esc(t('all'))}</option>`].concat((Info.go.generationOptions||[]).map(o=>`<option value="${esc(o.value)}" ${Info.pokedexGen==o.value?'selected':''}>${esc(o.label)}</option>`)).join('');
    const catOpts=[`<option value="all">${esc(t('all'))}</option>`].concat((Info.go.categoryOptions||[]).map(o=>`<option value="${esc(o.value)}" ${Info.pokedexCategory==o.value?'selected':''}>${esc(o.label)}</option>`)).join('');
    const sizeOpts=['50','100','200','500','all'].map(v=>`<option value="${v}" ${Info.pageSize===v?'selected':''}>${v==='all'?t('all'):v}</option>`).join('');
    panel.innerHTML=`<div class="nd-info-layout nd-pokedex-layout"><div class="nd-info-main"><h2>${esc(t('pokedex'))}</h2><div class="nd-pokedex-filters"><input class="nd-info-search" data-info-search="pokedex" placeholder="${esc(t('search'))}" value="${esc(Info.pokedexQuery)}"><label>${esc(t('generation'))}<select data-poke-filter="gen">${genOpts}</select></label><label>${esc(t('category'))}<select data-poke-filter="category">${catOpts}</select></label><label>${esc(t('pageSize'))}<select data-poke-filter="size">${sizeOpts}</select></label></div><p class="nd-info-count">${esc(t('showing'))} ${rows.length} / ${all.length} ${esc(t('rows'))}</p><div class="nd-table-scroll nd-pokedex-scroll"><table class="nd-data-table"><thead><tr><th>#</th><th>Name</th><th>简中</th><th>Form</th><th>Type</th><th>Gen</th><th>Atk</th><th>Def</th><th>HP</th><th>CP50</th></tr></thead><tbody>${rows.map((r,i)=>`<tr data-poke-index="${i}" class="${Info.selectedPokemon===r?'nd-selected-pokemon':''}"><td>${esc(r.dex)}</td><td>${esc(r.name)}</td><td>${esc(r.zhCN)}</td><td>${esc(r.form)}</td><td>${badge(r.type1)}${r.type2?badge(r.type2):''}</td><td>${esc(r.generation)}</td><td>${esc(r.goAttack)}</td><td>${esc(r.goDefense)}</td><td>${esc(r.goStamina)}</td><td>${esc(r.cp50)}</td></tr>`).join('')}</tbody></table></div></div><aside class="nd-info-side">${renderCalculator(Info.selectedPokemon)}</aside></div>`;
    const inp=panel.querySelector('[data-info-search="pokedex"]');
    inp.addEventListener('compositionstart',()=>{Info.composing=true;});
    inp.addEventListener('compositionend',()=>{Info.composing=false; Info.pokedexQuery=inp.value; renderPokedex(panel);});
    inp.addEventListener('input',()=>{ if(Info.composing) return; Info.pokedexQuery=inp.value; renderPokedex(panel); });
    panel.querySelector('[data-poke-filter="gen"]').addEventListener('change',e=>{ Info.pokedexGen=e.target.value; renderPokedex(panel); });
    panel.querySelector('[data-poke-filter="category"]').addEventListener('change',e=>{ Info.pokedexCategory=e.target.value; renderPokedex(panel); });
    panel.querySelector('[data-poke-filter="size"]').addEventListener('change',e=>{ Info.pageSize=e.target.value; renderPokedex(panel); });
    panel.querySelectorAll('[data-poke-index]').forEach(tr=>tr.addEventListener('click',()=>{ Info.selectedPokemon=rows[Number(tr.getAttribute('data-poke-index'))]; renderPokedex(panel); }));
    panel.querySelectorAll('[data-iv]').forEach(input=>input.addEventListener('input',()=>{ Info.iv[input.getAttribute('data-iv')]=Number(input.value); renderPokedex(panel); }));
    const level=panel.querySelector('[data-level]'); if(level) level.addEventListener('input',()=>{ const v=Math.max(1,Math.min(51,Math.round(Number(level.value||50)*2)/2)); Info.level=v; renderPokedex(panel); });
    if(!Info.composing){ inp.focus(); try{ inp.setSelectionRange(inp.value.length, inp.value.length); }catch(_){ } }
  }
  Info.exportTypes = async function(){ await loadData(); const types=Info.extra.types||[]; const rows=[["Attack \\ Defense"].concat(types.map(typeLabel))]; for(const at of types){ rows.push([typeLabel(at)].concat(types.map(df=>fmtMul(Info.extra.typeChart[at.key]?.[df.key]??1)))); } LDT_Core.downloadBlob('neatduck-type-chart.xlsx', LDT_Core.rowsToXLSXBlob(rows, 'type-chart')); };
  Info.exportPokedex = async function(){ await loadData(); const rows=[["dex","name","zh-CN","form","type1","type2","generation","category","goAttack","goDefense","goStamina","cp40","cp50"]].concat((Info.go.rows||[]).map(r=>[r.dex,r.name,r.zhCN,r.form,r.type1,r.type2,r.generation,(r.categories||[]).join('|'),r.goAttack,r.goDefense,r.goStamina,r.cp40,r.cp50])); LDT_Core.downloadBlob('neatduck-pokedex.xlsx', LDT_Core.rowsToXLSXBlob(rows, 'pokedex')); };
  Info.init=function(opts){ Info.opts=opts||{}; ensureUI(); };
  window.ND_Info=Info;
})();
