// == info.js v1.0.7 ==
(function(){
  const Info={mode:'calendar', extra:null, opts:{}, typeState:{attack:'fire', def1:'grass', def2:''}, filters:{pokedex:{q:'',gen:'all',cat:'all',size:'50'}, max:{q:'',gen:'all',cat:'all',size:'50'}}, selectedPokemon:null, iv:{atk:15,def:15,hp:15}, level:40};
  const labels={
    'zh-CN':{calendar:'Event Calendar',types:'属性克制',pokedex:'宝可梦图鉴',max:'极巨化',search:'搜索名称/编号/中文/日文',all:'全部',generation:'世代',category:'特殊类别',pageSize:'每页',exportCSV:'导出CSV',attackView:'攻击视角',defenseView:'防御视角',attackType:'攻击属性',defType1:'防御属性 1',defType2:'防御属性 2',none:'无',superEffective:'超级有效',effective:'有效',normal:'一般',resisted:'无效',superResisted:'超级无效',selectPokemon:'先从左侧选择宝可梦',cpCalc:'CP 计算器',level:'等级',ivAtk:'攻击 IV',ivDef:'防御 IV',ivHp:'体力 IV',cp:'CP',source:'数据源/公式',missing:'缺省',mega:'可 Mega',dmax:'可 Dynamax',gmax:'可 Gigantamax',legendary:'传说',mythical:'幻之',ultra:'究极异兽',goStats:'GO种族值',notice:'缺省或估算值会明确标记，毕竟数据不会因为我们盯着它就突然诚实。',maxNotice:'极巨招式由小招属性决定；实时可用名单和技能数值需以 Game Master / Pokémon GO API / 当前 Max Battles 数据为准。'},
    'zh-TW':{calendar:'Event Calendar',types:'屬性克制',pokedex:'寶可夢圖鑑',max:'極巨化',search:'搜尋名稱/編號/中文/日文',all:'全部',generation:'世代',category:'特殊類別',pageSize:'每頁',exportCSV:'匯出CSV',attackView:'攻擊視角',defenseView:'防禦視角',attackType:'攻擊屬性',defType1:'防禦屬性 1',defType2:'防禦屬性 2',none:'無',superEffective:'超級有效',effective:'有效',normal:'一般',resisted:'無效',superResisted:'超級無效',selectPokemon:'先從左側選擇寶可夢',cpCalc:'CP 計算器',level:'等級',ivAtk:'攻擊 IV',ivDef:'防禦 IV',ivHp:'體力 IV',cp:'CP',source:'資料源/公式',missing:'缺省',mega:'可 Mega',dmax:'可 Dynamax',gmax:'可 Gigantamax',legendary:'傳說',mythical:'幻之',ultra:'究極異獸',goStats:'GO種族值',notice:'缺省或估算值會明確標記。',maxNotice:'極巨招式由小招屬性決定；即時名單和技能數值需以 Game Master / Pokémon GO API / 目前 Max Battles 資料為準。'},
    en:{calendar:'Event Calendar',types:'Type Matchups',pokedex:'Pokédex',max:'Dynamax',search:'Search name, number, Chinese, Japanese',all:'All',generation:'Generation',category:'Special category',pageSize:'Rows',exportCSV:'Export CSV',attackView:'Attack view',defenseView:'Defense view',attackType:'Attack type',defType1:'Defender type 1',defType2:'Defender type 2',none:'None',superEffective:'Super effective',effective:'Effective',normal:'Neutral',resisted:'Resisted',superResisted:'Hard resisted',selectPokemon:'Select a Pokémon on the left first',cpCalc:'CP calculator',level:'Level',ivAtk:'Attack IV',ivDef:'Defense IV',ivHp:'HP IV',cp:'CP',source:'Source/formula',missing:'Missing',mega:'Mega',dmax:'Dynamax',gmax:'Gigantamax',legendary:'Legendary',mythical:'Mythical',ultra:'Ultra Beast',goStats:'GO stats',notice:'Missing or estimated values are explicitly marked, because apparently data needs supervision now.',maxNotice:'Max Moves are determined by fast-move type; live availability and move numbers should be refreshed from Game Master / Pokémon GO API / current Max Battles data.'}
  };
  const typeColors={normal:'#a8a77a',fire:'#ee8130',water:'#6390f0',electric:'#f7d02c',grass:'#7ac74c',ice:'#96d9d6',fighting:'#c22e28',poison:'#a33ea1',ground:'#e2bf65',flying:'#a98ff3',psychic:'#f95587',bug:'#a6b91a',rock:'#b6a136',ghost:'#735797',dragon:'#6f35fc',dark:'#705746',steel:'#b7b7ce',fairy:'#d685ad'};
  const CPM={1:0.094,1.5:0.135137432,2:0.16639787,2.5:0.192650919,3:0.21573247,3.5:0.236572661,4:0.25572005,4.5:0.273530381,5:0.29024988,5.5:0.306057377,6:0.3210876,6.5:0.335445036,7:0.34921268,7.5:0.362457751,8:0.37523559,8.5:0.387592406,9:0.39956728,9.5:0.411193551,10:0.42250001,10.5:0.432926419,11:0.44310755,11.5:0.4530599578,12:0.46279839,12.5:0.472336083,13:0.48168495,13.5:0.4908558,14:0.49985844,14.5:0.508701765,15:0.51739395,15.5:0.525942511,16:0.53435433,16.5:0.542635767,17:0.55079269,17.5:0.558830576,18:0.56675452,18.5:0.574569153,19:0.58227891,19.5:0.589887917,20:0.59740001,20.5:0.604818814,21:0.61215729,21.5:0.619399365,22:0.62656713,22.5:0.633644533,23:0.64065295,23.5:0.647576426,24:0.65443563,24.5:0.661214806,25:0.667934,25.5:0.674577537,26:0.68116492,26.5:0.687680648,27:0.69414365,27.5:0.700538673,28:0.70688421,28.5:0.713164996,29:0.71939909,29.5:0.725571552,30:0.7317,30.5:0.734741009,31:0.73776948,31.5:0.740785574,32:0.74378943,32.5:0.746781211,33:0.74976104,33.5:0.752729087,34:0.75568551,34.5:0.758630378,35:0.76156384,35.5:0.764486065,36:0.76739717,36.5:0.770297266,37:0.7731865,37.5:0.776064962,38:0.77893275,38.5:0.781790055,39:0.78463697,39.5:0.787473578,40:0.79030001,40.5:0.79280395,41:0.79530001,41.5:0.7978039,42:0.8003,42.5:0.8028039,43:0.8053,43.5:0.8078039,44:0.81029999,44.5:0.8128039,45:0.81529999,45.5:0.8178039,46:0.82029999,46.5:0.8228039,47:0.82529999,47.5:0.8278039,48:0.83029999,48.5:0.8328039,49:0.83529999,49.5:0.8378039,50:0.84029999};
  function lang(){ return (Info.opts.getLang&&Info.opts.getLang()) || (LDT_Core&&LDT_Core.DEFAULT_LANG) || 'zh-CN'; }
  function t(k){ const l=lang(); return (labels[l]||labels.en)[k] || labels.en[k] || k; }
  function esc(v){ return String(v==null?'':v).replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch])); }
  function val(v){ return (v==null || v==='') ? t('missing') : v; }
  function typeByKey(k){ return (Info.extra&&Info.extra.types||[]).find(x=>x.key===k); }
  function typeLabel(ty){ if(!ty) return ''; const l=lang(); return ty[l] || ty['zh-CN'] || ty.en || ty.key; }
  function badge(k){ const ty=typeByKey(k); if(!ty) return ''; return `<span class="nd-type-badge" style="--nd-type-color:${typeColors[k]||'#889'}">${esc(typeLabel(ty))}</span>`; }
  function fmtMul(v){ if(!isFinite(v)) return ''; const r=Math.round(v*100)/100; return String(r).replace(/\.00$/,'').replace(/(\.\d)0$/,'$1'); }
  function effClass(v){ if(v>=1.6) return 'nd-eff-high'; if(v>1) return 'nd-eff-mid'; if(Math.abs(v-1)<1e-9) return 'nd-eff-one'; if(v<0.625) return 'nd-eff-immune'; return 'nd-eff-low'; }
  function mult(atk,d1,d2){ const m=Info.extra.typeChart; if(!atk||!d1) return 1; return (m[atk]?.[d1]??1)*(d2?(m[atk]?.[d2]??1):1); }
  async function loadExtra(){ if(Info.extra) return Info.extra; let url='assets/pokemon_extra.json'; try{ if(chrome&&chrome.runtime&&chrome.runtime.getURL) url=chrome.runtime.getURL(url); }catch(_){} const r=await fetch(url); Info.extra=await r.json(); return Info.extra; }
  function ensureUI(){ const top=document.getElementById('ld-topbar'), right=document.getElementById('ld-right'), wrap=document.getElementById('ld-timeline-wrapper'); if(!top||!right||!wrap) return false; if(!document.getElementById('ld-info-panel')){ const p=document.createElement('div'); p.id='ld-info-panel'; p.style.display='none'; right.appendChild(p); } if(!top.__ndInfoBound){ top.addEventListener('click',ev=>{ const b=ev.target.closest('[data-info-mode]'); if(!b) return; ev.preventDefault(); Info.show(b.getAttribute('data-info-mode')); }); top.addEventListener('click',ev=>{ const b=ev.target.closest('[data-info-export]'); if(!b) return; ev.preventDefault(); Info.export(b.getAttribute('data-info-export')); }); top.__ndInfoBound=true; } return true; }
  function showControls(mode){ document.querySelectorAll('[data-tab-controls]').forEach(el=>{ el.style.display=el.getAttribute('data-tab-controls')===mode?'flex':'none'; }); document.querySelectorAll('[data-info-mode]').forEach(b=>b.classList.toggle('active', b.getAttribute('data-info-mode')===mode)); }
  function showCalendar(){ Info.mode='calendar'; showControls('calendar'); const p=document.getElementById('ld-info-panel'), wrap=document.getElementById('ld-timeline-wrapper'); if(p) p.style.display='none'; if(wrap) wrap.classList.remove('nd-info-active'); if(Info.opts.renderCalendar) Info.opts.renderCalendar(); else { const svg=document.getElementById('ld-timeline-svg'); if(svg) svg.style.display='block'; } }
  function showPanel(){ const p=document.getElementById('ld-info-panel'), wrap=document.getElementById('ld-timeline-wrapper'), svg=document.getElementById('ld-timeline-svg'), mg=document.getElementById('ld-monthgrid'); if(svg) svg.style.display='none'; if(mg) mg.style.display='none'; if(p) p.style.display='block'; if(wrap) wrap.classList.add('nd-info-active'); }
  Info.show=async function(mode){ if(!ensureUI()) return; if(mode==='calendar') return showCalendar(); Info.mode=mode; showControls(mode); showPanel(); await loadExtra(); render(mode); };
  Info.hide=showCalendar; Info.isInfoMode=()=>Info.mode&&Info.mode!=='calendar'; Info.refreshLabels=function(){ ensureUI(); showControls(Info.mode||'calendar'); if(Info.mode&&Info.mode!=='calendar') render(Info.mode); };
  function typeOptions(selected, none){ const arr=[]; if(none) arr.push(`<option value="">${esc(t('none'))}</option>`); for(const ty of Info.extra.types) arr.push(`<option value="${esc(ty.key)}" ${selected===ty.key?'selected':''}>${esc(typeLabel(ty))}</option>`); return arr.join(''); }
  function setDefense(k){ const st=Info.typeState; if(st.def1===k){ return; } if(st.def2===k){ st.def2=''; } else if(!st.def1){ st.def1=k; } else if(!st.def2){ st.def2=k; } else { st.def1=k; st.def2=''; } }
  function groupedIncoming(d1,d2){ const groups={superEffective:[],effective:[],normal:[],resisted:[],superResisted:[]}; for(const atk of Info.extra.types){ const v=mult(atk.key,d1,d2); const item={k:atk.key,v}; if(v>=1.6) groups.superEffective.push(item); else if(v>1) groups.effective.push(item); else if(Math.abs(v-1)<1e-9) groups.normal.push(item); else if(v<0.625) groups.superResisted.push(item); else groups.resisted.push(item); } return groups; }
  function renderTypes(){ const p=document.getElementById('ld-info-panel'), st=Info.typeState, types=Info.extra.types, chart=Info.extra.typeChart; const header=types.map(ty=>`<th class="${st.def1===ty.key||st.def2===ty.key?'nd-selected-col':''}" data-def="${esc(ty.key)}">${badge(ty.key)}</th>`).join(''); const rows=types.map(at=>`<tr><th class="${st.attack===at.key?'nd-selected-row':''}" data-atk="${esc(at.key)}">${badge(at.key)}</th>${types.map(df=>{ const v=chart[at.key]?.[df.key]??1; return `<td class="${effClass(v)} ${(st.attack===at.key?'nd-selected-rowcell':'')} ${(st.def1===df.key||st.def2===df.key?'nd-selected-colcell':'')}" data-atk="${esc(at.key)}" data-def="${esc(df.key)}">${fmtMul(v)}</td>`; }).join('')}</tr>`).join(''); const m=mult(st.attack,st.def1,st.def2); const groups=groupedIncoming(st.def1,st.def2); const groupHTML=Object.keys(groups).map(k=>`<div class="nd-defense-group"><h4>${esc(t(k))}</h4><div>${groups[k].map(x=>`<span class="nd-incoming-pill ${effClass(x.v)}">${badge(x.k)} <b>${fmtMul(x.v)}×</b></span>`).join('')||'<span class="nd-empty">-</span>'}</div></div>`).join(''); p.innerHTML=`<div class="nd-info-layout nd-types-layout"><div class="nd-info-main"><h2>${esc(t('types'))}</h2><div class="nd-table-scroll"><table class="nd-type-chart"><thead><tr><th>ATK\\DEF</th>${header}</tr></thead><tbody>${rows}</tbody></table></div></div><aside class="nd-info-side"><section class="nd-card nd-card-attack"><h3>${esc(t('attackView'))}</h3><label>${esc(t('attackType'))}<select data-type-control="attack">${typeOptions(st.attack,false)}</select></label><label>${esc(t('defType1'))}<select data-type-control="def1">${typeOptions(st.def1,false)}</select></label><label>${esc(t('defType2'))}<select data-type-control="def2">${typeOptions(st.def2,true)}</select></label><div class="nd-big-mult ${effClass(m)}">${fmtMul(m)}×</div><div>${badge(st.attack)} → ${badge(st.def1)} ${st.def2?badge(st.def2):''}</div></section><section class="nd-card nd-card-defense"><h3>${esc(t('defenseView'))}</h3><div class="nd-defense-summary">${badge(st.def1)} ${st.def2?badge(st.def2):''}</div>${groupHTML}</section></aside></div>`; p.querySelectorAll('[data-type-control]').forEach(sel=>sel.addEventListener('change',()=>{ st[sel.getAttribute('data-type-control')]=sel.value; if(sel.getAttribute('data-type-control')==='def1' && st.def2===st.def1) st.def2=''; renderTypes(); })); p.querySelectorAll('[data-atk]').forEach(el=>el.addEventListener('click',()=>{ st.attack=el.getAttribute('data-atk'); renderTypes(); })); p.querySelectorAll('[data-def]').forEach(el=>el.addEventListener('click',()=>{ setDefense(el.getAttribute('data-def')); renderTypes(); })); }
  function genOptions(sel){ const gs=(Info.extra.meta&&Info.extra.meta.generations)||[]; return `<option value="all">${esc(t('all'))}</option>`+gs.map(g=>`<option value="${g.id}" ${String(sel)===String(g.id)?'selected':''}>${g.id}. ${esc(g['zh-CN']||g.range)} · ${esc(g.games)}</option>`).join(''); }
  function catOptions(sel){ const cats=[['all',t('all')],['mega',t('mega')],['dmax',t('dmax')],['gmax',t('gmax')],['legendary',t('legendary')],['mythical',t('mythical')],['ultra',t('ultra')],['missing',t('missing')]]; return cats.map(c=>`<option value="${c[0]}" ${sel===c[0]?'selected':''}>${esc(c[1])}</option>`).join(''); }
  function sizeOptions(sel){ return ['50','100','200','500','all'].map(x=>`<option value="${x}" ${sel===x?'selected':''}>${x==='all'?t('all'):x}</option>`).join(''); }
  function filterRows(kind){ const f=Info.filters[kind], q=f.q.trim().toLowerCase(); let rows=(kind==='pokedex'?Info.extra.pokedex:Info.extra.max).filter(r=>{ const search=String(r.search||Object.values(r).join(' ')).toLowerCase(); if(q&&!search.includes(q)) return false; if(f.gen!=='all' && String(r.generation)!==String(f.gen)) return false; const cat=f.cat; if(cat==='mega'&&!r.canMega) return false; if(cat==='dmax'&&!(r.canDynamax||kind==='max')) return false; if(cat==='gmax'&&!(r.canGigantamax||r['超极巨技能'])) return false; if(cat==='legendary'&&!r.legendary) return false; if(cat==='mythical'&&!r.mythical) return false; if(cat==='ultra'&&!r.ultraBeast) return false; if(cat==='missing'&&!Object.values(r).some(v=>String(v)==='缺省'||String(v)==='')) return false; return true; }); return rows; }
  function limitedRows(kind){ const rows=filterRows(kind); const size=Info.filters[kind].size; return size==='all'?rows:rows.slice(0,Number(size)||50); }
  function cpFor(r){ const atk=Number(r['GO Attack']), def=Number(r['GO Defense']), sta=Number(r['GO Stamina']), c=CPM[Info.level]||CPM[40]; if(!isFinite(atk)||!isFinite(def)||!isFinite(sta)) return t('missing'); return Math.max(10, Math.floor((atk+Info.iv.atk)*Math.sqrt(def+Info.iv.def)*Math.sqrt(sta+Info.iv.hp)*c*c/10)); }
  function radarSVG(){ const cx=90,cy=78,R=54; const pts=['atk','def','hp'].map((k,i)=>{ const a=-Math.PI/2+i*2*Math.PI/3; const r=R*(Info.iv[k]/15); return [cx+Math.cos(a)*r,cy+Math.sin(a)*r,k]; }); const bg=[0,1,2].map(i=>{ const a=-Math.PI/2+i*2*Math.PI/3; return `${cx+Math.cos(a)*R},${cy+Math.sin(a)*R}`; }).join(' '); return `<svg class="nd-iv-radar" viewBox="0 0 180 145"><polygon points="${bg}" class="nd-radar-bg"></polygon><polygon points="${pts.map(p=>p[0]+','+p[1]).join(' ')}" class="nd-radar-poly"></polygon>${pts.map(p=>`<circle class="nd-radar-dot" data-iv="${p[2]}" cx="${p[0]}" cy="${p[1]}" r="7"></circle>`).join('')}<text x="90" y="15">ATK</text><text x="28" y="128">DEF</text><text x="142" y="128">HP</text></svg>`; }
  function renderCpPanel(r){ if(!r) return `<section class="nd-card"><h3>${esc(t('cpCalc'))}</h3><p>${esc(t('selectPokemon'))}</p></section>`; return `<section class="nd-card nd-cp-panel"><h3>${esc(t('cpCalc'))}: ${esc(r['zh-CN']||r.Name)}</h3><div class="nd-cp-stats">${esc(t('goStats'))}: ${val(r['GO Attack'])}/${val(r['GO Defense'])}/${val(r['GO Stamina'])}</div>${radarSVG()}<div class="nd-iv-controls">${[['atk',t('ivAtk')],['def',t('ivDef')],['hp',t('ivHp')]].map(x=>`<label>${esc(x[1])}<input type="number" min="0" max="15" data-iv-input="${x[0]}" value="${Info.iv[x[0]]}"><input type="range" min="0" max="15" data-iv-range="${x[0]}" value="${Info.iv[x[0]]}"></label>`).join('')}<label>${esc(t('level'))}<input type="number" min="1" max="50" step="0.5" data-level value="${Info.level}"></label></div><div class="nd-cp-result">${esc(t('cp'))}: <b>${esc(cpFor(r))}</b></div><p class="nd-info-note">CP=floor((Atk+IVAtk)×√(Def+IVDef)×√(Sta+IVSta)×CPM²/10)，最低 10。CPM 使用 Pokémon GO 等级乘数表。</p></section>`; }
  function renderPokedex(){ const p=document.getElementById('ld-info-panel'), f=Info.filters.pokedex, all=filterRows('pokedex'), rows=limitedRows('pokedex'); const selected=Info.selectedPokemon || rows[0]; if(!Info.selectedPokemon && selected) Info.selectedPokemon=selected; p.innerHTML=`<div class="nd-info-page nd-split-page"><div class="nd-info-main"><h2>${esc(t('pokedex'))}</h2><div class="nd-filterbar"><input data-filter="q" value="${esc(f.q)}" placeholder="${esc(t('search'))}"><select data-filter="gen">${genOptions(f.gen)}</select><select data-filter="cat">${catOptions(f.cat)}</select><select data-filter="size">${sizeOptions(f.size)}</select></div><p class="nd-info-note">${esc(t('notice'))} · ${rows.length}/${all.length}</p><div class="nd-table-scroll"><table class="nd-data-table"><thead><tr><th>#</th><th>Name</th><th>中文</th><th>${esc(t('generation'))}</th><th>Type</th><th>GO Atk</th><th>GO Def</th><th>GO Sta</th><th>LV40</th><th>LV50</th><th>Tag</th></tr></thead><tbody>${rows.map(r=>`<tr data-poke-row="${esc(r.Number+'|'+r.Name+'|'+(r.Form||''))}" class="${Info.selectedPokemon===r?'selected':''}"><td>${esc(r.Number)}</td><td>${esc(r.Name)} ${r.Form?`<small>${esc(r.Form)}</small>`:''}</td><td>${esc(r['zh-CN'])}</td><td>${esc(r.generation)} · ${esc(r.generationGames)}</td><td>${badge(r.type1Key)}${r.type2Key?badge(r.type2Key):''}</td><td>${val(r['GO Attack'])}</td><td>${val(r['GO Defense'])}</td><td>${val(r['GO Stamina'])}</td><td>${val(r['LV40 CP'])}</td><td>${val(r['LV50 CP'])}</td><td>${[r.canMega&&'Mega',r.canDynamax&&'DMax',r.canGigantamax&&'GMax',r.legendary&&'Legend',r.mythical&&'Mythic',r.ultraBeast&&'UB'].filter(Boolean).join(' / ')||''}</td></tr>`).join('')}</tbody></table></div></div><aside class="nd-info-side">${renderCpPanel(Info.selectedPokemon)}</aside></div>`; bindFilters('pokedex'); p.querySelectorAll('[data-poke-row]').forEach((tr,i)=>tr.addEventListener('click',()=>{ Info.selectedPokemon=rows[i]; renderPokedex(); })); bindCp(); }
  function bindFilters(kind){ const p=document.getElementById('ld-info-panel'); p.querySelectorAll('[data-filter]').forEach(el=>el.addEventListener(el.tagName==='INPUT'?'input':'change',()=>{ Info.filters[kind][el.getAttribute('data-filter')]=el.value; if(kind==='pokedex') Info.selectedPokemon=null; render(kind); })); }
  function bindCp(){ const p=document.getElementById('ld-info-panel'); p.querySelectorAll('[data-iv-input],[data-iv-range]').forEach(el=>el.addEventListener('input',()=>{ const k=el.getAttribute('data-iv-input')||el.getAttribute('data-iv-range'); Info.iv[k]=Math.max(0,Math.min(15,Number(el.value)||0)); renderPokedex(); })); const lev=p.querySelector('[data-level]'); if(lev) lev.addEventListener('input',()=>{ Info.level=Math.max(1,Math.min(50,Math.round((Number(lev.value)||40)*2)/2)); renderPokedex(); }); p.querySelectorAll('.nd-radar-dot').forEach(dot=>dot.addEventListener('click',()=>{ const k=dot.getAttribute('data-iv'); Info.iv[k]=(Info.iv[k]+1)%16; renderPokedex(); })); }
  function renderMax(){ const p=document.getElementById('ld-info-panel'), f=Info.filters.max, all=filterRows('max'), rows=limitedRows('max'); p.innerHTML=`<div class="nd-info-page"><h2>${esc(t('max'))}</h2><div class="nd-filterbar"><input data-filter="q" value="${esc(f.q)}" placeholder="${esc(t('search'))}"><select data-filter="gen">${genOptions(f.gen)}</select><select data-filter="cat">${catOptions(f.cat)}</select><select data-filter="size">${sizeOptions(f.size)}</select></div><p class="nd-info-note">${esc(t('maxNotice'))} · ${rows.length}/${all.length}</p><div class="nd-table-scroll"><table class="nd-data-table"><thead><tr><th>名称</th><th>${esc(t('generation'))}</th><th>Type</th><th>LV40</th><th>LV50</th><th>攻击</th><th>0.5s 小招</th><th>极巨技能</th><th>Max伤害</th><th>超极巨技能</th><th>GMax伤害</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r['名称'])}</td><td>${esc(r.generation||'')} · ${esc(r.generationGames||'')}</td><td>${badge(r.type1Key)}${r.type2Key?badge(r.type2Key):''}</td><td>${val(r['LV40 CP'])}</td><td>${val(r['LV50 CP'])}</td><td>${val(r['攻击'])}</td><td>${val(r['0.5s 小招'])}</td><td>${esc([r['极巨技能1'],r['极巨技能2']].filter(x=>x&&x!=='缺省').join(' / ')||'缺省')}</td><td>${esc([r['Max伤害1'],r['Max伤害2']].filter(x=>x&&x!=='缺省').join(' / ')||'缺省')}</td><td>${val(r['超极巨技能'])}</td><td>${val(r['GMax伤害'])}</td></tr>`).join('')}</tbody></table></div></div>`; bindFilters('max'); }
  function toCSV(rows){ const cols=Array.from(rows.reduce((s,r)=>{ Object.keys(r).forEach(k=>s.add(k)); return s; }, new Set())); const escCSV=v=>{ const x=String(v==null?'':v); return /[",\r\n]/.test(x)?'"'+x.replace(/"/g,'""')+'"':x; }; return cols.join(',')+'\n'+rows.map(r=>cols.map(c=>escCSV(r[c])).join(',')).join('\n')+'\n'; }
  Info.export=function(mode){ loadExtra().then(()=>{ let text=''; if(mode==='types'){ const rows=[]; for(const atk of Info.extra.types){ const row={attack:typeLabel(atk)}; for(const df of Info.extra.types) row[typeLabel(df)]=fmtMul(mult(atk.key,df.key,'')); rows.push(row); } text=toCSV(rows); } else text=toCSV(filterRows(mode)); const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'})); a.download=`neatduck-${mode}.csv`; document.body.appendChild(a); a.click(); setTimeout(()=>{URL.revokeObjectURL(a.href); a.remove();},0); }); };
  function render(mode){ if(mode==='types') renderTypes(); else if(mode==='pokedex') renderPokedex(); else if(mode==='max') renderMax(); }
  Info.init=function(opts){ Info.opts=opts||{}; ensureUI(); showControls(Info.mode||'calendar'); };
  window.ND_Info=Info;
})();
