// == info.js v1.0.7 ==
(function(){
  const Info = {
    extra:null,
    mode:"calendar",
    hooks:{getLang:()=>"zh-CN"},
    typeState:{attack:"fire", def1:"grass", def2:""},
    dex:{query:"", gen:"all", category:"all", pageSize:100, selected:null, iv:{attack:15,defense:15,stamina:15}, level:50},
    labels:{
      "zh-CN":{calendar:"活动日历",types:"属性克制",pokedex:"宝可梦图鉴",exportTypes:"导出属性CSV",exportDex:"导出图鉴CSV",atk:"攻击视角",def:"防御视角",attackType:"攻击属性",defenseCombo:"防御属性组合",super2:"超级有效",super:"有效",normal:"一般",resist:"抗性",resist2:"超级抗性",search:"搜索中文/英文/编号",allGen:"全部世代",allCat:"全部类别",mega:"可 Mega",legendary:"传说宝可梦",mythical:"幻之宝可梦",form:"可变换形态",fusion:"可合体",verified:"有 Pokémon GO CP数据",rows:"显示行数",selectPokemon:"从左侧表格选择一个宝可梦",cpCalc:"CP 计算器",level:"等级",iv:"IV",goStatsMissing:"这条没有可靠 Pokémon GO 种族值，暂不计算 CP。",cpFormula:"公式：CP = floor((Atk+IVa) × sqrt(Def+IVd) × sqrt(Sta+IVs) × CPM² / 10)，最低 10。CPM 表随等级读取。",cpNote:"注：你给的 13/15/15 Lv50 藏玛然特 CP=4681 匹配王盾/Crowned Shield 数据，不匹配百战勇者/Hero 数据。"},
      "zh-TW":{calendar:"活動日曆",types:"屬性克制",pokedex:"寶可夢圖鑑",exportTypes:"匯出屬性CSV",exportDex:"匯出圖鑑CSV",atk:"攻擊視角",def:"防禦視角",attackType:"攻擊屬性",defenseCombo:"防禦屬性組合",super2:"超級有效",super:"有效",normal:"一般",resist:"抗性",resist2:"超級抗性",search:"搜尋中文/英文/編號",allGen:"全部世代",allCat:"全部類別",mega:"可 Mega",legendary:"傳說寶可夢",mythical:"幻之寶可夢",form:"可變換形態",fusion:"可合體",verified:"有 Pokémon GO CP資料",rows:"顯示列數",selectPokemon:"從左側表格選擇一隻寶可夢",cpCalc:"CP 計算器",level:"等級",iv:"IV",goStatsMissing:"這筆沒有可靠 Pokémon GO 種族值，暫不計算 CP。",cpFormula:"公式：CP = floor((Atk+IVa) × sqrt(Def+IVd) × sqrt(Sta+IVs) × CPM² / 10)，最低 10。CPM 表隨等級讀取。",cpNote:"註：你給的 13/15/15 Lv50 藏瑪然特 CP=4681 符合王盾/Crowned Shield 資料，不符合百戰勇者/Hero 資料。"},
      "en":{calendar:"Event Calendar",types:"Type Matchup",pokedex:"Pokédex",exportTypes:"Export Type CSV",exportDex:"Export Pokédex CSV",atk:"Attack view",def:"Defense view",attackType:"Attack type",defenseCombo:"Defense type combo",super2:"Double super effective",super:"Super effective",normal:"Neutral",resist:"Resisted",resist2:"Double resisted",search:"Search Chinese/English/#",allGen:"All generations",allCat:"All categories",mega:"Can Mega",legendary:"Legendary",mythical:"Mythical",form:"Form change",fusion:"Fusion",verified:"Verified Pokémon GO CP data",rows:"Rows",selectPokemon:"Select a Pokémon from the table",cpCalc:"CP Calculator",level:"Level",iv:"IV",goStatsMissing:"No reliable Pokémon GO base stats for this row yet, so CP is not calculated.",cpFormula:"Formula: CP = floor((Atk+IVa) × sqrt(Def+IVd) × sqrt(Sta+IVs) × CPM² / 10), minimum 10. CPM is read by level.",cpNote:"Note: your 13/15/15 Lv50 Zamazenta CP=4681 matches Crowned Shield data, not Hero of Many Battles data."}
    }
  };
  function lang(){ return (Info.hooks.getLang && Info.hooks.getLang()) || "zh-CN"; }
  function L(k){ const d=Info.labels[lang()]||Info.labels["zh-CN"]; return d[k]||k; }
  function esc(s){ return String(s==null?"":s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m])); }
  function typeName(t){ const row=(Info.extra&&Info.extra.types||[]).find(x=>x.key===t); if(!row) return t; return lang()==="en"?row.en:(lang()==="zh-TW"?row["zh-TW"]:row["zh-CN"]); }
  function typeColor(t){ const row=(Info.extra&&Info.extra.types||[]).find(x=>x.key===t); return (row&&row.color)||"#999"; }
  function badge(t){ return `<span class="nd-type-badge" style="background:${esc(typeColor(t))};color:${textColor(typeColor(t))}">${esc(typeName(t))}</span>`; }
  function textColor(hex){ try{ const h=String(hex).replace('#',''); const r=parseInt(h.slice(0,2),16),g=parseInt(h.slice(2,4),16),b=parseInt(h.slice(4,6),16); return (0.2126*r+0.7152*g+0.0722*b)<145?'#fff':'#111'; }catch(_){return '#111';} }
  async function loadExtra(){ if(Info.extra) return Info.extra; try{ const url=(typeof chrome!=="undefined"&&chrome.runtime)?chrome.runtime.getURL("assets/pokemon_go.json"):"assets/pokemon_go.json"; Info.extra=await (await fetch(url)).json(); }catch(e){ console.warn("pokemon_go.json unavailable",e); Info.extra={types:[],typeChart:{},pokedex:[],cpm:{"50":0.84029999},cpVerification:[]}; } return Info.extra; }
  function panel(){ let p=document.getElementById("nd-info-panel"); const right=document.getElementById("ld-right"); if(!p&&right){ p=document.createElement("div"); p.id="nd-info-panel"; p.style.display="none"; right.appendChild(p); } return p; }
  function switchToolbars(mode){ document.querySelectorAll('.nd-tab').forEach(b=>b.classList.toggle('active',b.getAttribute('data-nd-tab')===mode)); document.querySelectorAll('.nd-tab-toolbar').forEach(r=>{ r.style.display = r.getAttribute('data-toolbar')===mode ? 'flex' : 'none'; }); }
  function showChrome(mode){ const wrap=document.getElementById('ld-timeline-wrapper'); const left=document.getElementById('ld-left'); const svg=document.getElementById('ld-timeline-svg'); const mg=document.getElementById('ld-monthgrid'); const p=panel(); Info.mode=mode; switchToolbars(mode); if(wrap) wrap.classList.toggle('nd-info-mode', mode!=="calendar"); if(mode==="calendar"){ if(left) left.style.display="block"; if(p) p.style.display="none"; if(window.ND_renderCalendar) window.ND_renderCalendar(); return; } if(left) left.style.display="none"; if(svg) svg.style.display="none"; if(mg) mg.style.display="none"; if(p){ p.style.display="block"; p.onwheel=e=>e.stopPropagation(); p.onclick=e=>e.stopPropagation(); } }
  function multiplier(atk, def1, def2){ const c=Info.extra.typeChart||{}; const m1=Number(c[atk]&&c[atk][def1]||1); const m2=def2?Number(c[atk]&&c[atk][def2]||1):1; return m1*m2; }
  function fmtM(v){ return Number(v).toFixed(2).replace(/\.00$/,'').replace(/0$/,''); }
  function selectedDefLabel(){ return [Info.typeState.def1,Info.typeState.def2].filter(Boolean).map(typeName).join(' / '); }
  function setDefense(t){ if(t===Info.typeState.def1){ Info.typeState.def1=Info.typeState.def2||t; Info.typeState.def2=""; }
    else if(t===Info.typeState.def2){ Info.typeState.def2=""; }
    else if(!Info.typeState.def1){ Info.typeState.def1=t; }
    else if(!Info.typeState.def2){ Info.typeState.def2=t; }
    else { Info.typeState.def1=t; Info.typeState.def2=""; }
    if(Info.typeState.def1===Info.typeState.def2) Info.typeState.def2="";
  }
  function renderTypes(){ showChrome('types'); const p=panel(); const types=(Info.extra.types||[]).map(x=>x.key); const bar=document.querySelector('[data-toolbar="types"]'); if(bar) bar.innerHTML=`<button class="btn" data-info-action="export-types">📤 ${esc(L('exportTypes'))}</button>`; const rows=types.map(atk=>`<tr class="${atk===Info.typeState.attack?'sel-row':''}"><th data-atk="${atk}">${badge(atk)}</th>${types.map(def=>`<td class="${def===Info.typeState.def1||def===Info.typeState.def2?'sel-col':''}" data-atk="${atk}" data-def="${def}">${fmtM(multiplier(atk,def,''))}</td>`).join('')}</tr>`).join(''); p.innerHTML=`<div class="nd-info-grid nd-types-layout"><div class="nd-heatwrap"><table class="nd-type-heatmap"><thead><tr><th></th>${types.map(t=>`<th data-def="${t}" class="${t===Info.typeState.def1||t===Info.typeState.def2?'sel-col':''}">${badge(t)}</th>`).join('')}</tr></thead><tbody>${rows}</tbody></table></div><div class="nd-type-side"><section class="nd-attack-card"><h3>${esc(L('atk'))}</h3><p>${esc(L('attackType'))}: ${badge(Info.typeState.attack)}</p><p>${esc(L('defenseCombo'))}: ${[Info.typeState.def1,Info.typeState.def2].filter(Boolean).map(badge).join(' ')}</p><div class="nd-big-mult">×${fmtM(multiplier(Info.typeState.attack,Info.typeState.def1,Info.typeState.def2))}</div></section><section><h3>${esc(L('def'))}: ${esc(selectedDefLabel())}</h3><div id="nd-defense-groups"></div></section></div></div>`; renderDefenseGroups(); p.querySelectorAll('[data-atk]').forEach(el=>el.addEventListener('click',()=>{Info.typeState.attack=el.getAttribute('data-atk'); if(el.getAttribute('data-def')) setDefense(el.getAttribute('data-def')); renderTypes();})); p.querySelectorAll('[data-def]').forEach(el=>el.addEventListener('click',()=>{setDefense(el.getAttribute('data-def')); renderTypes();})); document.querySelector('[data-info-action="export-types"]')?.addEventListener('click', exportTypes); }
  function renderDefenseGroups(){ const types=(Info.extra.types||[]).map(x=>x.key); const groups={super2:[],super:[],normal:[],resist:[],resist2:[]}; types.forEach(atk=>{ const m=multiplier(atk,Info.typeState.def1,Info.typeState.def2); const item={atk,m}; if(m>=2.5) groups.super2.push(item); else if(m>1.01) groups.super.push(item); else if(m<0.45) groups.resist2.push(item); else if(m<0.99) groups.resist.push(item); else groups.normal.push(item); }); const el=document.getElementById('nd-defense-groups'); if(!el) return; el.innerHTML=['super2','super','normal','resist','resist2'].map(k=>`<div class="nd-def-group"><b>${esc(L(k))}</b><div>${groups[k].map(x=>badge(x.atk)).join(' ')||'—'}</div></div>`).join(''); }
  function exportTypes(){ const types=(Info.extra.types||[]).map(x=>x.key); const rows=[['attack',...types].join(',')].concat(types.map(a=>[a,...types.map(d=>fmtM(multiplier(a,d,'')))].join(','))); download('neatduck-type-matchup.csv', rows.join('\n'), 'text/csv;charset=utf-8'); }
  function download(name,text,type){ const url=URL.createObjectURL(new Blob([text],{type:type||'text/plain'})); const a=document.createElement('a'); a.href=url; a.download=name; document.body.appendChild(a); a.click(); a.remove(); URL.revokeObjectURL(url); }
  function dexRows(){ let rows=Info.extra.pokedex||[]; const q=Info.dex.query.trim().toLowerCase(); if(q) rows=rows.filter(r=>String(r.search||'').toLowerCase().includes(q)||String(r.name_zh_cn||'').includes(Info.dex.query)||String(r.name_zh_tw||'').includes(Info.dex.query)); if(Info.dex.gen!=='all') rows=rows.filter(r=>String(r.generation)===Info.dex.gen); if(Info.dex.category!=='all') rows=rows.filter(r=>Info.dex.category==='verified'?!!r.goStats:(r.categories||[]).includes(Info.dex.category)); return rows; }
  function nameOf(r){ return lang()==='en'?r.name:(lang()==='zh-TW'?(r.name_zh_tw||r.name):(r.name_zh_cn||r.name)); }
  function renderPokedex(){ showChrome('pokedex'); const p=panel(); const bar=document.querySelector('[data-toolbar="pokedex"]'); const gens=[...new Set((Info.extra.pokedex||[]).map(r=>r.generation).filter(Boolean))].sort((a,b)=>a-b); if(bar) bar.innerHTML=`<input class="btn nd-search" id="nd-dex-search" placeholder="${esc(L('search'))}" value="${esc(Info.dex.query)}"><select class="btn" id="nd-gen"><option value="all">${esc(L('allGen'))}</option>${gens.map(g=>`<option value="${g}" ${String(g)===Info.dex.gen?'selected':''}>第${g}世代 · ${esc((Info.extra.meta.generationGames||{})[g]||'')}</option>`).join('')}</select><select class="btn" id="nd-cat"><option value="all">${esc(L('allCat'))}</option><option value="mega">${esc(L('mega'))}</option><option value="legendary">${esc(L('legendary'))}</option><option value="mythical">${esc(L('mythical'))}</option><option value="form_change">${esc(L('form'))}</option><option value="fusion">${esc(L('fusion'))}</option><option value="verified">${esc(L('verified'))}</option></select><select class="btn" id="nd-size"><option>50</option><option>100</option><option>200</option><option>500</option><option value="all">全部</option></select><button class="btn" data-info-action="export-dex">📤 ${esc(L('exportDex'))}</button>`; const all=dexRows(); const n=Info.dex.pageSize==='all'?all.length:Number(Info.dex.pageSize||100); const rows=all.slice(0,n); if(!Info.dex.selected && rows[0]) Info.dex.selected=rows[0]; p.innerHTML=`<div class="nd-info-grid nd-dex-layout"><div class="nd-dex-table-wrap"><table class="nd-dex-table"><thead><tr><th>#</th><th>名称</th><th>Form</th><th>Type</th><th>Gen</th><th>GO Atk/Def/Sta</th></tr></thead><tbody>${rows.map((r,i)=>`<tr data-dex-index="${i}" class="${Info.dex.selected===r?'selected':''}"><td>${esc(r.number)}</td><td>${esc(nameOf(r))}<br><small>${esc(r.name)}</small></td><td>${esc(r.form||'')}</td><td>${(r.types||[]).map(badge).join(' ')}</td><td title="${esc(r.generationGames||'')}">${esc(r.generation)}</td><td>${r.goStats?`${r.goStats.attack}/${r.goStats.defense}/${r.goStats.stamina}`:'—'}</td></tr>`).join('')}</tbody></table></div><div class="nd-cp-panel">${renderCP()}</div></div>`; p.querySelectorAll('[data-dex-index]').forEach(tr=>tr.addEventListener('click',()=>{Info.dex.selected=rows[Number(tr.getAttribute('data-dex-index'))]; renderPokedex();})); bindDexControls(); }
  function bindDexControls(){ const q=document.getElementById('nd-dex-search'); if(q&&!q.__b){ q.addEventListener('input',()=>{Info.dex.query=q.value; Info.dex.selected=null; renderPokedex();}); q.__b=true;} const g=document.getElementById('nd-gen'); if(g){g.value=Info.dex.gen; g.onchange=()=>{Info.dex.gen=g.value; Info.dex.selected=null; renderPokedex();};} const c=document.getElementById('nd-cat'); if(c){c.value=Info.dex.category; c.onchange=()=>{Info.dex.category=c.value; Info.dex.selected=null; renderPokedex();};} const s=document.getElementById('nd-size'); if(s){s.value=String(Info.dex.pageSize); s.onchange=()=>{Info.dex.pageSize=s.value==='all'?'all':Number(s.value); renderPokedex();};} document.querySelector('[data-info-action="export-dex"]')?.addEventListener('click', exportDex); bindCPControls(); }
  function calcCP(r){ if(!r||!r.goStats) return null; const cpm=Number((Info.extra.cpm||{})[String(Info.dex.level)]||0); if(!cpm) return null; const s=r.goStats, iv=Info.dex.iv; return Math.max(10, Math.floor((s.attack+iv.attack)*Math.sqrt(s.defense+iv.defense)*Math.sqrt(s.stamina+iv.stamina)*cpm*cpm/10)); }
  function renderCP(){ const r=Info.dex.selected; if(!r) return `<h3>${esc(L('cpCalc'))}</h3><p>${esc(L('selectPokemon'))}</p>`; const cp=calcCP(r); return `<h3>${esc(L('cpCalc'))}</h3><div class="nd-cp-title"><b>${esc(nameOf(r))}</b><small>${esc(r.name)} ${esc(r.form||'')}</small></div>${r.goStats?`<p>GO Stats: ${r.goStats.attack}/${r.goStats.defense}/${r.goStats.stamina}</p><div class="nd-iv-rose" id="nd-iv-rose"><svg viewBox="0 0 220 190"><polygon points="110,18 25,165 195,165" fill="rgba(0,0,0,.04)" stroke="#98a2b3"/><text x="110" y="12" text-anchor="middle">Atk ${Info.dex.iv.attack}</text><text x="18" y="181">Def ${Info.dex.iv.defense}</text><text x="170" y="181">Sta ${Info.dex.iv.stamina}</text></svg></div><label>${esc(L('level'))} <input id="nd-level" type="range" min="1" max="50" step="0.5" value="${Info.dex.level}"> ${Info.dex.level}</label><label>Atk <input data-iv="attack" type="range" min="0" max="15" value="${Info.dex.iv.attack}"> ${Info.dex.iv.attack}</label><label>Def <input data-iv="defense" type="range" min="0" max="15" value="${Info.dex.iv.defense}"> ${Info.dex.iv.defense}</label><label>Sta <input data-iv="stamina" type="range" min="0" max="15" value="${Info.dex.iv.stamina}"> ${Info.dex.iv.stamina}</label><div class="nd-cp-result">CP ${cp==null?'—':cp}</div>`:`<p>${esc(L('goStatsMissing'))}</p>`}<p class="nd-cp-formula">${esc(L('cpFormula'))}</p><p class="nd-cp-note">${esc(L('cpNote'))}</p><details><summary>验证样例</summary>${(Info.extra.cpVerification||[]).map(v=>`<div>${esc(v.label)}: ${v.computedCP} ${v.pass?'✅':'❌'}</div>`).join('')}</details>`; }
  function bindCPControls(){ document.querySelectorAll('[data-iv]').forEach(inp=>inp.oninput=()=>{Info.dex.iv[inp.getAttribute('data-iv')]=Number(inp.value); renderPokedex();}); const lvl=document.getElementById('nd-level'); if(lvl) lvl.oninput=()=>{Info.dex.level=Number(lvl.value); renderPokedex();}; const rose=document.getElementById('nd-iv-rose'); if(rose) rose.onclick=(ev)=>{ const rect=rose.getBoundingClientRect(); const x=(ev.clientX-rect.left)/rect.width, y=(ev.clientY-rect.top)/rect.height; const pts={attack:[0.5,0.08],defense:[0.12,0.86],stamina:[0.88,0.86]}; let best='attack',bd=9; for(const k of Object.keys(pts)){ const dx=x-pts[k][0],dy=y-pts[k][1],d=dx*dx+dy*dy; if(d<bd){bd=d;best=k;} } const cx=0.5, cy=0.58; const dist=Math.sqrt((x-cx)*(x-cx)+(y-cy)*(y-cy)); Info.dex.iv[best]=Math.max(0,Math.min(15,Math.round(dist/0.48*15))); renderPokedex(); }; }
  function exportDex(){ const rows=dexRows(); const head=['id','name','zh_cn','form','type1','type2','generation','goAttack','goDefense','goStamina','categories']; const body=rows.map(r=>[r.id,r.name,r.name_zh_cn,r.form,r.type1,r.type2,r.generation,r.goStats?.attack||'',r.goStats?.defense||'',r.goStats?.stamina||'',(r.categories||[]).join('|')].map(x=>`"${String(x).replace(/"/g,'""')}"`).join(',')); download('neatduck-pokedex.csv',[head.join(','),...body].join('\n'),'text/csv;charset=utf-8'); }
  Info.show=async function(mode){ await loadExtra(); if(mode==='types') renderTypes(); else if(mode==='pokedex') renderPokedex(); else showChrome('calendar'); };
  Info.hide=function(){ if(Info.mode!=="calendar") Info.show('calendar'); };
  Info.refreshLabels=function(){ if(Info.mode==='types') renderTypes(); if(Info.mode==='pokedex') renderPokedex(); };
  Info.init=async function(hooks){ Info.hooks=hooks||Info.hooks; await loadExtra(); document.querySelectorAll('[data-nd-tab]').forEach(btn=>{ if(!btn.__ndBound){ btn.addEventListener('click',()=>Info.show(btn.getAttribute('data-nd-tab'))); btn.__ndBound=true; } }); switchToolbars('calendar'); };
  window.ND_Info=Info;
})();
